### ISSUE TITLE
JavaScript error Certificate Template Designer

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/sensei-certificates#84]
Ticket here: https://woothemes.zendesk.com/agent/tickets/389792

to reproduce
1. Certificates -> Certificate Templates -> add nee
2. press 'set position'

result: http://cld.wthms.co/1js3G/2XcWMuU5

@danjjohnson @dwainm

**Comment by danjjohnson** [comment]
Thanks @WillBrubaker 

You need to set a Certificate background image before setting the position of each section.

Ideally the certificate data metabox should remain hidden until the background image is set, so I'll leave this issue open for that.

**Comment by WillBrubaker** [comment]
@danjjohnson 

That doesn't seem to work either. I have set a background image with the same result. Also tried with the included "Example Template" with the same result. Customer also reports that they have set a background image and are experiencing this behaviour.

**Comment by WillBrubaker** [comment]
@danjjohnson have you had a chance to circle back to this?

**Comment by danjjohnson** [comment]
Hey @WillBrubaker It's still working fine for me:
![certs](https://cloud.githubusercontent.com/assets/1990037/13497966/ccfd5676-e14f-11e5-94f2-ce84c63aca8c.gif)

Any chance it could be a plugin conflict or something?

**Comment by WillBrubaker** [comment]
@danjjohnson 

>Any chance it could be a plugin conflict or something?

No, it is not. It is a failure on my part to understand how this is supposed to work. Thank you very much for the screencast :)

**Comment by danjjohnson** [comment]
Thanks @WillBrubaker - It's not as intuitive as it could be :)
